# Generated by Django 5.2.5 on 2025-08-13 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('grado', models.CharField(blank=True, max_length=2)),
                ('tipo_capita', models.CharField(default='Común', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_capita', models.CharField(choices=[('Común', 'Común'), ('Social', 'Social')], max_length=20, unique=True)),
                ('precio_por_capita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO')], max_length=7)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(default='Capita', max_length=60)),
                ('comentario', models.CharField(blank=True, max_length=200)),
                ('miembro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('estado', models.CharField(choices=[('pagada', 'pagada'), ('debe', 'debe'), ('exento', 'exento')], default='debe', max_length=10)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.miembro')),
            ],
            options={
                'unique_together': {('miembro', 'anio', 'mes')},
            },
        ),
    ]
