# Generated by Django 5.2.5 on 2025-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='paga_desde',
            field=models.DateField(blank=True, help_text='Primera fecha desde la que debe pagar; meses previos del mismo año quedan exentos.', null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='tipo_capita',
            field=models.CharField(choices=[('Común', 'Común'), ('Social', 'Social'), ('Exenta', 'Exenta')], default='Común', max_length=20),
        ),
    ]
